#!/bin/bash
# do test

if [ $# -ne 2 ] ; then
    echo "usage: dotest <input_file> <baseline_file>"
    exit
fi

~/src/deva/test $1 > '$$$RESULTS$$$'

if cmp -s '$$$RESULTS$$$' $2 ; then
    echo "test succeeded"
    rm -f '$$$RESULTS$$$'
    exit
else
    echo "test failed"
    rm -f '$$$RESULTS$$$'
    exit -1
fi
