#!/bin/bash
# do test using devac (deva compiler) as the program to run

if [ $# -ne 2 ] ; then
    echo "usage: dotest <input_file> <baseline_file>"
    exit
fi

# TODO: shareable path to devac
~/src/deva/devac -r3 --debug-dump on $1 > '$$$RESULTS$$$'

if cmp -s '$$$RESULTS$$$' $2 ; then
    echo "test succeeded"
	# TODO: generate filename ('input.dvc') from $1 arg
    rm -f '$$$RESULTS$$$' 'input.dvc'
    exit
else
    echo "test failed"
	# TODO: generate filename ('input.dvc') from $1 arg
    rm -f '$$$RESULTS$$$' 'input.dvc'
    exit -1
fi
