#!/bin/bash
# do test using devac (deva compiler) to compile and then deva (deva executor)
# to execute the program

if [ $# -ne 2 ] ; then
    echo "usage: dotest <input_file> <baseline_file>"
    exit
fi

if [ -z $DEVA ] ; then
	echo "DEVA environment variable must be set to point to the directory where 'deva' is installed"
	exit
fi

$DEVA/deva $1 > '$$$RESULTS$$$'

if cmp -s '$$$RESULTS$$$' $2 ; then
    echo "test succeeded"
	# TODO: generate filename ('input.dvc') from $1 arg
    rm -f '$$$RESULTS$$$'
	rm -f *.dvc
    exit
else
    echo "test failed"
	# TODO: generate filename ('input.dvc') from $1 arg
    rm -f '$$$RESULTS$$$'
	rm -f *.dvc
    exit -1
fi
