#!/bin/bash
# do test

if [ $# -ne 2 ] ; then
    echo "usage: dotest <input_file> <baseline_file>"
    exit
fi

if [ -z $DEVA ] ; then
	echo "DEVA environment variable must be set to point to the directory where 'deva' is installed"
	exit
fi

$DEVA/test $1 > '$$$RESULTS$$$'

if cmp -s '$$$RESULTS$$$' $2 ; then
    echo "test succeeded"
    rm -f '$$$RESULTS$$$'
    exit
else
    echo "test failed"
    rm -f '$$$RESULTS$$$'
    exit -1
fi
