#!/bin/bash
# do test using valgrind on deva (deva executor) to execute the program
# ONLY ensures the code is valgrind clean (or no 'dirtier' than the baseline
# anyway), doesn't ensure the test ran correctly otherwise (use the normal
# dotest_exec script for that)

if [ $# -ne 1 ] ; then
    echo "usage: dotest_valgrind <input_file>"
    exit
fi

# TODO: shareable path to deva
valgrind --leak-check=yes --suppressions=/home/jcs/src/deva/valgrind.supp ~/src/deva/deva $1 2> '$$$RESULTS$$$' > /dev/null

if grep -q "ERROR SUMMARY: 0 errors from 0 contexts" '$$$RESULTS$$$'; then
    echo "test succeeded"
    rm -f '$$$RESULTS$$$'
	rm -f *.dvc
    exit
else
    echo "test failed"
    rm -f '$$$RESULTS$$$'
	rm -f *.dvc
    exit -1
fi

