#!/bin/bash
# do test using devac (deva compiler) as the program to run

if [ $# -ne 2 ] ; then
    echo "usage: dotest <input_file> <baseline_file>"
    exit
fi

if [ -z $DEVA ] ; then
	echo "DEVA environment variable must be set to point to the directory where 'deva' is installed"
	exit
fi

$DEVA/devac -r3 --debug-dump on $1 > '$$$RESULTS$$$'

if diff -I ^.*\.table.*$ '$$$RESULTS$$$' $2 ; then
    echo "test succeeded"
	# TODO: generate filename ('input.dvc') from $1 arg
    rm -f '$$$RESULTS$$$' 'input.dvc'
    exit
else
    echo "test failed"
	# TODO: generate filename ('input.dvc') from $1 arg
    rm -f '$$$RESULTS$$$' 'input.dvc'
    exit -1
fi
