#!/usr/bin/python
# python script to run all the deva lang tests

import os

home = os.getenv( "HOME" )
dotest = os.path.join( home, "src/deva/dotest" )
init_dir = os.getcwd()

# run 'dotest input.dv baseline' in each sub-dir
for root, dir, files in os.walk( os.path.join( os.getcwd(), "tests" ) ):
    if "baseline" in files:
        print( "processing " + root + " ..." )
        os.chdir( root )
        os.spawnl( os.P_WAIT, dotest, "dotest", "input.dv", "baseline" )
        
os.chdir( init_dir )
