#!/bin/sh
# compile foo.dv
../../deva -c foo.dv
# move foo.dvc into bar directory, for import during test
mkdir bar
mv foo.dvc bar/foo.dvc
# run the test
../../dotest_exec $1 $2
# delete bar/foo.dvc
rm bar/foo.dvc
# delete the bar dir
rmdir bar
